name: Deploy Infrastructure

# the workflow to execute on is comments that are newly created
on:
  issue_comment:
    types: [created]

# permissions needed for reacting to IssueOps commands on issues and PRs
permissions:
  pull-requests: write
  issues: write
  checks: read

jobs:
  deploy_infra:
    runs-on: ubuntu-latest
    steps:
      
    - uses: github/command@v1.2.2
      id: command
      with:
        command: ".deploy"
        reaction: "rocket"
        allowed_contexts: "issue"
        permissions: "maintain,admin"
        allowlist: 0gis0

    - name: deploy
      run: echo "I am going to deploy now!"