name: Deploy Infrastructure

on:
  issue_comment:
    types: [created]


defaults:
  run:
    working-directory: ./terraform

env:
  ARM_SUBSCRIPTION_ID: ${{ secrets.TF_SUBSCRIPTION_ID }}
  ARM_CLIENT_ID: ${{ secrets.TF_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.TF_CLIENT_SECRET }}
  ARM_TENANT_ID: ${{ secrets.TF_TENANT_ID }} 

permissions:
  contents: read
  issues: write
  actions: read

jobs:
  deploy_infra:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: github/command@v1.2.2
      id: command
      with:
        command: ".deploy"
        reaction: "rocket"
        allowed_contexts: "issue"
        permissions: "maintain,admin"
        allowlist: 0gis0

    - name: deploy
      run: echo "I am going to deploy now!"

    - name: Find Comments
      id: fc
      uses: boringresearch/find-comments@v1
      with:    
        issue-number: ${{ github.event.issue.number }}      
        comment-author: github-actions    
        body-includes: Run ID
  
    - name: show run id
      run: |
          echo "Comment ID: ${{ steps.fc.outputs.comment-id }}"
          echo ${{ steps.fc.outputs.comment-node-id }}
          echo "Comment Body: ${{ steps.fc.outputs.comment-body }}"
          echo ${{ steps.fc.outputs.comment-author }}
          echo ${{ steps.fc.outputs.comment-created-at }}
      

    - name: Download artifact related with this issue
      uses: actions/download-artifact@v4.1.8
      with:
        name: artifact
        run-id: 11963924274
        
    - name: List files in artifact
      run: ls ${{ github.workspace }}/artifact

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Terraform Init
      id: init
      run: | 
        terraform init

    - name: Terraform Apply     
      id: apply
      run: |
        terraform apply -auto-approve artifact/tfplan.out
