name: Deploy Infrastructure

on:
  issue_comment:
    types: [created]


defaults:
  run:
    working-directory: ./terraform

env:
  ARM_SUBSCRIPTION_ID: ${{ secrets.TF_SUBSCRIPTION_ID }}
  ARM_CLIENT_ID: ${{ secrets.TF_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.TF_CLIENT_SECRET }}
  ARM_TENANT_ID: ${{ secrets.TF_TENANT_ID }} 

permissions:
  contents: read
  issues: write
  checks: read

jobs:
  deploy_infra:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: github/command@v1.2.2
      id: command
      with:
        command: ".deploy"
        reaction: "rocket"
        allowed_contexts: "issue"
        permissions: "maintain,admin"
        allowlist: 0gis0

    - name: deploy
      run: echo "I am going to deploy now!"

    - name: Find  the comment with the run id
      uses: peter-evans/find-comment@v3
      id: fc
      with:
        issue-number: ${{ github.event.issue.number }}
        body-includes: "Run ID:"

    - name: Get the run id from the comment
      id: run_id
      run: echo "${{ steps.fc.outputs.body }}"

    - name: show run id
      run: echo ${{ steps.run_id.outputs.run_id }}

    - name: Download artifact related with this issue
      uses: actions/download-artifact@v4
      with:
        name: artifact
        run-id: ${{ steps.run_id.outputs.run_id }}

    - name: List files in artifact
      run: ls ${{ github.workspace }}/artifact

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Terraform Init
      id: init
      run: | 
        terraform init

    - name: Terraform Apply     
      id: apply
      run: |
        terraform apply -auto-approve artifact/tfplan.out
